### ISSUE TITLE
Unable to add some addons

### ISSUE THREAD

**Issue by flesk** [gdraynz/wowui#5]
first of all thank you, thats a pretty sweet little app. lets hope it doesn't hit any cloudflare limits, but it looks good, jscript to the rescue.

![image](https://user-images.githubusercontent.com/340199/65541470-b5d95980-df0d-11e9-96bb-aa14d3ca7698.png)

			"280790": {
				"id": 280790,
				"name": "Aptechka",
				"version": null,
				"downloadCount": 8207,
				"websiteUrl": "https://www.curseforge.com/wow/addons/aptechka"

		"wowinterface": {
			"25050": {
				"id": "25050",
				"name": "Aptechka Classic",
				"version": "1.13.13",
				"latestVersion": "1.13.13",
				"downloadUrl": "https://cdn.wowinterface.com/downloads/getfile.php?id=25050&d=1569122112&minion",
				"downloadCount": "3160",
				"websiteUrl": null
			}

also i tried to replace the "null" values with valid values but it did not reproduce into the app.

thank you,

flesk

**Comment by gdraynz** [comment]
Unfortunatly I can't really deal with missing informations from Curseforge... it got all kinds of different fields that all give the same informations that sometimes are relevant and sometimes not. x_x

**Comment by flesk** [comment]
ah ok I thought its a parsing thing, is there a logfile somewhere in roaming?

had that problem serveral times now

Spinx Bag Space
Titan Panel Classic

**Comment by flesk** [comment]
and just added them without any problems, strange one. will try some more and report, might just be curseapi
